name: demo jobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: enter the name
         run: echo "My name is Kaviya"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "deloy the app"
    
    
   
