name: demo jobs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: enter the name
         run: |
           echo "My name is ${{ vars.NAME }}"
           echo "I am working in TCS"
